### PR TITLE
Adding Azure DevOps badge

### LINKED ISSUE #182: Add Azure Pipelines badge to README.md
The deploy is now done with Azure Pipelines. We should add a badge to the README.

### PR DESCRIPTION
**Pull request by MattMattV**
Used https://github.com/badges/shields, set the Azure DevOps icons

Should close #182

### CODE REVIEW

**Comment by MattMattV** [comment]
is it possible to have the `hacktoberfest-accepted` label ?

**Comment by libremente** [comment]
What's the status of this one @bfabio?

**Comment by bfabio** [comment]
@libremente looks good, but I want to double check it

**Comment by bfabio** [comment]
@MattMattV thanks for the PR, sorry I didn't notice your request for the Hacktoberfest label :(

**Pull request merged**
