### PR TITLE
Added LibreOffice powered by CIB

### PR DESCRIPTION
**Pull request by deneb-alpha**
Added the external repo for LibreOffice powered by CIB

### CODE REVIEW

**Comment by libremente** [comment]
Thanks @deneb-alpha!
Merging now squashing to one commit 👍

**Comment by deneb-alpha** [comment]
Hi @libremente, thanks for the merge. I was looking at the catalogue but the software isn't listed.
Do you know when the crawler should include it?
Please, check also the related issue: https://github.com/italia/developers-italia-backend/issues/97

**Comment by deneb-alpha** [comment]
Hello @libremente, @biancini, @alranel. This patch is merged but the software is still not listed in the catalogue. Are there updates on this issue?  @biancini told me on slack that could be an issue related to this: https://github.com/alranel/go-vcsurl/issues/2 
Do you have any ETA for the fix?

**Comment by libremente** [comment]
Hi @deneb-alpha, correct, unfortunately the issue you are raising is connected to the issue on the library you cited. This is affecting the publication of both software (libreoffice and libreoffice powered by CIB). We are currently on a high load so I am not able to give you an ETA right now but it is our priority to fix such an issue. I will get back to you ASAP. Thanks!

**Comment by deneb-alpha** [comment]
hi @libremente. sorry for poking you again on this issue but it's really sad to see that some products are just excluded from the catalogue for this issue.  
Do you have any update?

**Pull request merged**
