### PR TITLE
Adding Knowage: Open Source Suite for modern Business Analytics

### PR DESCRIPTION
**Pull request by davide-zerbetto**
Proposal to add Knowage to third party software list. Knowage is an open source suite for modern Business Analytics.
Website: https://www.knowage-suite.com/site/home/
Success stories: https://www.knowage-suite.com/site/resources/success-stories/
Repository: https://github.com/KnowageLabs/Knowage-Server

### CODE REVIEW

**Comment by libremente** [comment]
Hi @davide-zerbetto, I'm reporting the results of the validation on your publiccode.yml:
```
validation ko:
maintenance/contractors: HTTP GET returned 503 for https://www.enav.it/sites/public/it/Home.html; 200 was expected
```
Could you please check and fix this before going on in the process?
Thanks

**Comment by davide-zerbetto** [comment]
Hi @libremente, ENAV website is not working, but I do not have control on it. Let's wait a bit to see if it goes back online...

**Comment by davide-zerbetto** [comment]
Hi @libremente, ENAV website is back online. Could you please try to validate the publiccode.yml file?

**Comment by libremente** [comment]
Hi @davide-zerbetto, validation is working now. Could you please rebase and fix the commits? I'll merge straight after that. Thanks!

**Comment by davide-zerbetto** [comment]
Hi @libremente,
done.
Thanks

**Pull request merged**
