### PR TITLE
Ported crawler diagram to mermaid syntax

### PR DESCRIPTION
**Pull request by MattMattV**
When clicking on the diagram, the live editor will be opened for easy edition.*

The live editor also provide configuration edition, to customize sizes, fonts and colors.

Should make some progress on #194

### CODE REVIEW

**Comment by bfabio** [comment]
@MattMattV Thanks for the PR! :heart: 

There's something wrong with the Markdown: the diagram doesn't render https://github.com/italia/developers-italia-backend/blob/32027d07616cb64423c4c64aa65d915f34aba78a/docs/crawler.md

**Comment by MattMattV** [comment]
Just looked into it, the image URI is too long for GitHub caching/proxying service, you can see the 414 error in the browser dev tools :disappointed:

**Comment by MattMattV** [comment]
One solution would be to use any URL shortener

**Comment by MattMattV** [comment]
is it possible to have the `hacktoberfest-accepted` label ?

**Comment by bfabio** [comment]
@MattMattV Sure, we'll figure out what to do with the long URL.

**Comment by bfabio** [comment]
@MattMattV Merged (and used a link shortener in #206). Thanks!

**Pull request merged**
