### PR TITLE
added FastReport  to white list

### PR DESCRIPTION
**Pull request by 8VAid8**
FastReport provides open source report generator for .NET Core 2.x/.NET Framework 4.x. You can use the FastReport in MVC, Web API applications.

### CODE REVIEW

**Comment by libremente** [comment]
Hi @8VAid8 and thanks for your interest!
Quick question: since I don't see a `dependsOn` key in your `publiccode.yml` file, I am wondering whether the software you want to insert is completely standalone or has some dependencies (open/proprietary).

**Comment by 8VAid8** [comment]
It has dependencies from .Net Core, CoreCompat.System.Drawing.v2. But i didn't think this dependencies are essential (first one is a framework, second - open source library (MIT) ) and have to be added to `dependsOn ` key.
You can find all references in files:
`https://github.com/FastReports/FastReport/blob/master/FastReport.OpenSource/FastReport.OpenSource.csproj`, `https://github.com/FastReports/FastReport/blob/master/FastReport.Core.Web/FastReport.Web.csproj`

So, should we add .Net Core or/and CoreCompat.System.Drawing.v2 to the `dependsOn ` key?

**Comment by 8VAid8** [comment]
And Dependency graph - https://github.com/FastReports/FastReport/network/dependencies

**Comment by libremente** [comment]
Hi @8VAid8, after checking your `publiccode.yml`, it looks like there are still some problems. I'd suggest you to load your `publiccode.yml` inside our editor https://publiccode-editor.developers.italia.it/ and fix such problems. 
I am pasting below the problems seen:
```bash
validation ko:
invalid key: Unexpected array key: tags
monochromeLogo: the monochromeLogo is not monochrome (black): https://github.com/FastReports/FastReport/blob/master/assets/images/FR-open-source-bw.svg
invalid key: Unexpected string key: publiccode-yaml-version
description/it/screenshots: Absolute URL (https://raw.githubusercontent.com/FastReports/FastReport.Documentation/master/images/FastReport-screenshot2.png) is outside the repository (https://raw.githubusercontent.com/FastReports/FastReport/master/)
description/en/longDescription: too short (339), min 500 chars
description/en/screenshots: Absolute URL (https://raw.githubusercontent.com/FastReports/FastReport.Documentation/master/images/FastReport-screenshot2.png) is outside the repository (https://raw.githubusercontent.com/FastReports/FastReport/master/)
```

Let me know how can I further assist you. Thanks

**Comment by 8VAid8** [comment]
Thank you, @libremente ! I've fixed our publiccode.yml and your editor says it looks ok (i can't get any errors there).

**Comment by libremente** [comment]
Thanks @8VAid8, merging.

**Pull request merged**
