### PR TITLE
add: readd io-app later on its migration to pagopa org

### PR DESCRIPTION
**Pull request by sebbalex**

### CODE REVIEW

**Comment by sebbalex** [comment]
thinking about it, however, it could be the case to add the entire organization, @bfabio @libremente wdyt?

**Review by bfabio — APPROVED** [review]
:+1:

**Comment by bfabio** [comment]
@sebbalex I think it makes sense on principle. As of today there's another repo with a publiccode.yml in it: https://github.com/search?q=user%3Apagopa+path%3A%2F+filename%3Apubliccode.yml&type=Code&ref=advsearch&l=&l=

**Comment by sebbalex** [comment]
> @sebbalex I think it makes sense on principle. As of today there's another repo with a publiccode.yml in it: https://github.com/search?q=user%3Apagopa+path%3A%2F+filename%3Apubliccode.yml&type=Code&ref=advsearch&l=&l=

that's true but we could help them and create some `publiccode.yml` in their repos

**Comment by libremente** [comment]
@sebbalex yes, I'd add the whole org. I think we can open a few issues to ask them to compose some publiccode.yml files in the relevant repos

**Review by bfabio — APPROVED** [review]
:+1:

**Review by libremente — APPROVED** [review]

**Pull request merged**
