### PR TITLE
Update docs

### LINKED ISSUE #171: Update crawler documentation
The [docs](https://github.com/italia/developers-italia-backend/tree/master/docs) folder contains very outdated infos. We should update most of them

### PR DESCRIPTION
**Pull request by bfabio**
I took the nuclear option and removed the files: IMHO they don't add much of value to the `README.md`.

I'm not sure about `mappingElasticsearch.md`. Is it up to date?

Fix #171

### CODE REVIEW

**Comment by libremente** [comment]
I am not 100% sure that we want to remove all those files. Is the updating effort too high?

**Comment by bfabio** [comment]
Indeed I should've added a little more rationale:

#### [**`docs/crawler.md`**](https://github.com/italia/developers-italia-backend/blob/master/docs/crawler.md)

Has three parts:
* A sequence diagram that IMHO doesn't add much to the mental model you build reading `README.md`. Intstead it gives the impression there's more to grasp and the logic is more complicated, when it's actually not.
* A verbatim copy of the built in help
* A section restating what happens in needless detail when you run the crawler. If there's something of interest here (as in, there's something against the principle of least astonishment, but it doesn't look like it to me), it should be moved to the README or to comments in the source code.

#### [**`docs/fileAndFolders.md`**](https://github.com/italia/developers-italia-backend/blob/master/docs/fileAndFolders.md)

It's mostly stuff along the lines of `.git` being the git directory, `vitality-ranges.yml` being the "ranges for vitality index" (duh) and `CRAWLER_DATADIR` containing the the data of the crawler. 

#### [**`docs/jekyll.md`**](https://github.com/italia/developers-italia-backend/blob/master/docs/jekyll.md)

The Jekyll part doesn't apply to this repo

The File generation part is actually relevant and thinking about it we should probably move it to the README. 

#### [**`docs/references.md`**](https://github.com/italia/developers-italia-backend/blob/master/docs/references.md)

Seems pretty superfluous, restating thinks either in the README or in the very files it mentions.

**Comment by libremente** [comment]
I kinda like the idea of the diagram in /crawler because it can be an example for PAs of what kind of documentation you can insert in github. Of course this holds just if those info are updated, if not let's remove it.
Ok for the rest, I'd try to move the relevant info in the README file and the remove the folder as you're proposing.

**Comment by sebbalex** [comment]
I agree to keep the crawler diagram, only if it is updated. As of now it does not have latest features but the entire process is described as it is. Do we have somewhere the source of that graph?

**Comment by bfabio** [comment]
@libremente  

> I kinda like the idea of the diagram in /crawler because it can be an example for PAs of what kind of documentation you can insert in github. Of course this holds just if those info are updated, if not let's remove it.

Ok, I kept the diagram in `crawler.md`. :+1: 

> Ok for the rest, I'd try to move the relevant info in the README file and afterwards remove the folder as you're proposing.

Moved the good part of `jekyll.md` to the README. Note that the directory was never removed because we still need the vitality files there.

**Comment by bfabio** [comment]
> I agree to keep the crawler diagram, only if it is updated. As of now it does not have latest features but the entire process is described as it is. Do we have somewhere the source of that graph?

AFAICT it's updated, as far `crawl` mode is concerned. I'm afraid it's just an image shared with https://www.websequencediagrams.com and we have no source.

On second thought we should probably put it into the repo, wdyt?

**Comment by libremente** [comment]
I really believe we should use https://mermaid-js.github.io/mermaid/ for this kind of diagrams

**Comment by bfabio** [comment]
@libremente 100% agree

**Comment by bfabio** [comment]
@sebbalex @libremente OK to merge?

**Comment by sebbalex** [comment]
@bfabio I'm not 100% convinced about [**`docs/references.md`**](https://github.com/italia/developers-italia-backend/blob/master/docs/references.md) file. It adds some folder and file structure information that is actually not well covered in README file.

**Comment by bfabio** [comment]
@sebbalex are you for keeping it or for integrating it into the README?

**Comment by sebbalex** [comment]
> @sebbalex are you for keeping it or for integrating it into the README?

I'm for keeping it simple so I'd merge it into README :)

**Comment by bfabio** [comment]
@sebbalex Moved the non-duplicate info to README.

**Review by sebbalex — APPROVED** [review]
:+1:

**Pull request merged**
